CREATE PROFILE "PRO_APP"
LIMIT
 COMPOSITE_LIMIT UNLIMITED
 SESSIONS_PER_USER UNLIMITED
 CPU_PER_SESSION UNLIMITED
 CPU_PER_CALL UNLIMITED
 LOGICAL_READS_PER_SESSION UNLIMITED
 LOGICAL_READS_PER_CALL UNLIMITED
 IDLE_TIME UNLIMITED
 CONNECT_TIME UNLIMITED
 PRIVATE_SGA UNLIMITED
 FAILED_LOGIN_ATTEMPTS 5
 PASSWORD_LIFE_TIME UNLIMITED
 PASSWORD_REUSE_TIME 30
 PASSWORD_REUSE_MAX 5
 PASSWORD_VERIFY_FUNCTION NULL
 PASSWORD_LOCK_TIME 1
 PASSWORD_GRACE_TIME 7;