/*===========CREAR LOS ROLES==================*/

CREATE ROLE ROL_ADMIN;
CREATE ROLE ROL_ANALISTA;
CREATE ROLE ROL_SOPORTE;
CREATE ROLE ROL_CONTENIDO;

/*======PRIVILEGIOS PARA ROL_ADMIN========*/

GRANT SELECT, INSERT, UPDATE, DELETE ON Usuario TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Perfil TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Contenido TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Temporada TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Episodio TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Reproduccion TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Pago TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Calificacion TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Favorito TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Reporte TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Genero TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Categoria TO ROL_ADMIN;

GRANT CREATE SESSION TO ROL_ADMIN;
GRANT CREATE USER TO ROL_ADMIN;
GRANT ALTER USER TO ROL_ADMIN;
GRANT DROP USER TO ROL_ADMIN;


/*======PRIVILEGIOS PARA ROL_ANALISTA========*/

GRANT SELECT ON Usuario TO ROL_ANALISTA;
GRANT SELECT ON Perfil TO ROL_ANALISTA;
GRANT SELECT ON Contenido TO ROL_ANALISTA;
GRANT SELECT ON Reproduccion TO ROL_ANALISTA;
GRANT SELECT ON Pago TO ROL_ANALISTA;
GRANT SELECT ON Calificacion TO ROL_ANALISTA;
GRANT SELECT ON Reporte TO ROL_ANALISTA;

GRANT CREATE SESSION TO ROL_ANALISTA;

/*=======Privilegios para el Rol Soporte*/

GRANT SELECT ON Usuario TO ROL_SOPORTE;
GRANT SELECT ON Perfil TO ROL_SOPORTE;
GRANT SELECT ON Pago TO ROL_SOPORTE;
GRANT SELECT ON Suscripcion TO ROL_SOPORTE;

GRANT INSERT, UPDATE ON Pago TO ROL_SOPORTE;

GRANT CREATE SESSION TO ROL_SOPORTE;

/*======PRIVILEGIOS PARA ROL_CONTENIDO======*/

GRANT SELECT, INSERT, UPDATE, DELETE ON Contenido TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON Temporada TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON Episodio TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON Genero TO ROL_CONTENIDO;

GRANT SELECT ON Reproduccion TO ROL_CONTENIDO;
GRANT SELECT ON Calificacion TO ROL_CONTENIDO;

GRANT CREATE SESSION TO ROL_CONTENIDO;

/*===========CREAR USUARIOS============*/

CREATE USER admin_stream IDENTIFIED BY Admin123;
CREATE USER analista_stream IDENTIFIED BY Analista123;
CREATE USER soporte_stream IDENTIFIED BY Soporte123;
CREATE USER contenido_stream IDENTIFIED BY Contenido123;

/*====ASIGNAR ROLES=====*/

GRANT ROL_ADMIN TO admin_stream;
GRANT ROL_ANALISTA TO analista_stream;
GRANT ROL_SOPORTE TO soporte_stream;
GRANT ROL_CONTENIDO TO contenido_stream;

/*=======ESPACIO EN TABLESPACE===========*/

ALTER USER admin_stream QUOTA UNLIMITED ON USERS;
ALTER USER analista_stream QUOTA UNLIMITED ON USERS;
ALTER USER soporte_stream QUOTA UNLIMITED ON USERS;
ALTER USER contenido_stream QUOTA UNLIMITED ON USERS;

/*====CREAR PROFILE===*/

CREATE PROFILE PERFIL_STREAM LIMIT
    SESSIONS_PER_USER 2
    CONNECT_TIME 60
    IDLE_TIME 15
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 30;
    
/*====ASIGNAR PROFILE====*/

ALTER USER admin_stream PROFILE PERFIL_STREAM;
ALTER USER analista_stream PROFILE PERFIL_STREAM;
ALTER USER soporte_stream PROFILE PERFIL_STREAM;
ALTER USER contenido_stream PROFILE PERFIL_STREAM;

/*=======DEMOSTRACIÓN DEL ERROR===========*/

DELETE FROM Contenido
WHERE id_contenido = 1;



