-- ======================================================================
-- SPRINT 5: CONTROL DE ACCESO BASADO EN ROLES (RBAC) - QUINDIOFLIX
-- RESPONSABLE: TEAM MEMBER 3 (security.sql)
-- ======================================================================

-- 1. LIMPIEZA DE ROLES PREVIOS (Evita errores de duplicidad al reejecutar)
BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROL_ADMIN_QUINDIOFLIX';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROL_CLIENTE_QUINDIOFLIX';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 2. CREACIÓN DE ROLES CORPORATIVOS
CREATE ROLE ROL_ADMIN_QUINDIOFLIX;
CREATE ROLE ROL_CLIENTE_QUINDIOFLIX;

-- 3. ASIGNACIÓN DE PRIVILEGIOS AL ROL ADMINISTRADOR (Control Total)
GRANT SELECT, INSERT, UPDATE, DELETE ON Usuario TO ROL_ADMIN_QUINDIOFLIX;
GRANT SELECT, INSERT, UPDATE, DELETE ON Suscripcion TO ROL_ADMIN_QUINDIOFLIX;
GRANT SELECT, INSERT, UPDATE, DELETE ON Contenido TO ROL_ADMIN_QUINDIOFLIX;
GRANT SELECT, INSERT, UPDATE, DELETE ON Perfil TO ROL_ADMIN_QUINDIOFLIX;
GRANT SELECT, INSERT, UPDATE, DELETE ON Reproduccion TO ROL_ADMIN_QUINDIOFLIX;
GRANT SELECT, INSERT, UPDATE, DELETE ON Calificacion TO ROL_ADMIN_QUINDIOFLIX;

-- Permitir que el admin ejecute tu procedimiento de reportes
GRANT EXECUTE ON SP_REPORTE_CONSUMO TO ROL_ADMIN_QUINDIOFLIX;

-- 4. ASIGNACIÓN DE PRIVILEGIOS AL ROL CLIENTE (Solo Lectura y Consumo Seguro)
GRANT SELECT ON Contenido TO ROL_CLIENTE_QUINDIOFLIX;
GRANT SELECT ON Perfil TO ROL_CLIENTE_QUINDIOFLIX;
GRANT SELECT, INSERT ON Reproduccion TO ROL_CLIENTE_QUINDIOFLIX;
GRANT SELECT, INSERT, UPDATE ON Calificacion TO ROL_CLIENTE_QUINDIOFLIX;

PROMPT Roles 'ROL_ADMIN_QUINDIOFLIX' y 'ROL_CLIENTE_QUINDIOFLIX' creados y configurados con éxito.