CREATE PROFILE "PRO_USER"
LIMIT
 COMPOSITE_LIMIT UNLIMITED
 SESSIONS_PER_USER 1
 CPU_PER_SESSION UNLIMITED
 CPU_PER_CALL 4000 -- (0.01*4000) -> 40 segundos en CPU
 LOGICAL_READS_PER_SESSION UNLIMITED
 LOGICAL_READS_PER_CALL UNLIMITED
 IDLE_TIME 30 -- Luego de 30 min inactividad expulsa la sesión
 CONNECT_TIME UNLIMITED
 PRIVATE_SGA UNLIMITED
 FAILED_LOGIN_ATTEMPTS 5
 PASSWORD_LIFE_TIME 90
 PASSWORD_REUSE_TIME 365
 PASSWORD_REUSE_MAX 4
 PASSWORD_LOCK_TIME 1
 PASSWORD_GRACE_TIME 5;