-- ===================================================================== --
-- Archivo para la generación de registros necesarios para contenido     --
-- Contenido, Generos, Temporadas, Episodios y relaciones                --
-- Contiene 40 contenidos, 20 temporadas y 80 episodios                  --
-- ===================================================================== --

INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (100, 100, 101, 'Ultimo Cafe', 'Pelicula regional', '+13', DATE '2020-01-01', 'S');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (101, 100, 102, 'Ruta Cafetera', 'Pelicula regional', '+7', DATE '2021-02-02', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (102, 100, 101, 'Noche Roja', 'Pelicula regional', '+18', DATE '2022-03-03', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (103, 100, 102, 'Finca Feliz', 'Pelicula regional', '+7', DATE '2023-04-04', 'S');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (104, 100, 101, 'Amanecer Verde', 'Pelicula regional', '+13', DATE '2024-05-05', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (105, 100, 102, 'Rio de Sombras', 'Pelicula regional', '+16', DATE '2020-06-06', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (106, 100, 101, 'Ciudad Armenia', 'Pelicula regional', 'TP', DATE '2021-07-07', 'S');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (107, 100, 102, 'Tren del Cafe', 'Pelicula regional', '+13', DATE '2022-08-08', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (108, 100, 101, 'Casa en Salento', 'Pelicula regional', '+7', DATE '2023-09-09', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (109, 100, 102, 'Lluvia de Abril', 'Pelicula regional', 'TP', DATE '2024-10-10', 'S');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (110, 100, 101, 'Puente Viejo', 'Pelicula regional', '+13', DATE '2020-11-11', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (111, 100, 102, 'Cosecha Final', 'Pelicula regional', '+16', DATE '2021-12-12', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (112, 100, 101, 'Risa Paisa', 'Pelicula regional', '+7', DATE '2022-01-13', 'S');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (113, 100, 102, 'Sombra Andina', 'Pelicula regional', '+18', DATE '2023-02-14', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (114, 100, 101, 'Corazon Quindio', 'Pelicula regional', '+13', DATE '2024-03-15', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (115, 101, 101, 'Codigo Andino', 'Serie original', '+16', DATE '2020-01-01', 'S');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (116, 101, 102, 'Cyber City', 'Serie original', '+16', DATE '2021-02-02', 'S');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (117, 101, 101, 'Aula Digital', 'Serie original', 'TP', DATE '2022-03-03', 'S');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (118, 101, 102, 'Familia Cafe', 'Serie original', '+7', DATE '2023-04-04', 'S');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (119, 101, 101, 'Red Oscura', 'Serie original', '+18', DATE '2024-05-05', 'S');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (120, 101, 102, 'Campus 360', 'Serie original', '+13', DATE '2020-06-06', 'S');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (121, 101, 101, 'Startup Armenia', 'Serie original', '+13', DATE '2021-07-07', 'S');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (122, 101, 102, 'Guardia Verde', 'Serie original', 'TP', DATE '2022-08-08', 'S');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (123, 101, 101, 'Datos Cruzados', 'Serie original', '+16', DATE '2023-09-09', 'S');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (124, 101, 102, 'Liga Cafetera', 'Serie original', '+7', DATE '2024-10-10', 'S');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (125, 102, 102, 'Historia Quindio', 'Documental regional', 'TP', DATE '2020-01-01', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (126, 102, 102, 'Volcan Nevado', 'Documental regional', '+7', DATE '2021-02-02', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (127, 102, 102, 'Paisaje Cafetero', 'Documental regional', 'TP', DATE '2022-03-03', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (128, 102, 102, 'Aves del Otun', 'Documental regional', '+7', DATE '2023-04-04', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (129, 102, 102, 'Memoria Armenia', 'Documental regional', 'TP', DATE '2024-05-05', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (130, 102, 102, 'Eje Innovador', 'Documental regional', '+7', DATE '2020-06-06', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (131, 102, 102, 'Rios de Caldas', 'Documental regional', 'TP', DATE '2021-07-07', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (132, 102, 102, 'Cultura Cafetera', 'Documental regional', '+7', DATE '2022-08-08', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (133, 103, 102, 'Tech Talks', 'Podcast regional', '+7', DATE '2020-01-01', 'S');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (134, 103, 102, 'Cafe Podcast', 'Podcast regional', 'TP', DATE '2021-02-02', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (135, 103, 102, 'Voces UQ', 'Podcast regional', 'TP', DATE '2022-03-03', 'S');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (136, 103, 102, 'Emprende Eje', 'Podcast regional', '+7', DATE '2023-04-04', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (137, 103, 102, 'Historias TI', 'Podcast regional', 'TP', DATE '2024-05-05', 'S');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (138, 103, 102, 'Data al Dia', 'Podcast regional', 'TP', DATE '2020-06-06', 'N');
INSERT INTO Contenido (id_contenido, id_tipo_categoria, id_empleado_publicador, titulo, sipnosis, clasificacion_edad, fecha_lanzamiento, es_original) VALUES (139, 103, 102, 'Mesa Regional', 'Podcast regional', '+7', DATE '2021-07-07', 'S');
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (100, 115, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (100, 100, 'E1 T1 115', 50, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (101, 100, 'E1 T1 115', 51, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (102, 100, 'E1 T1 115', 52, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (103, 100, 'E1 T1 115', 38, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (101, 115, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (104, 101, 'E2 T2 115', 51, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (105, 101, 'E2 T2 115', 52, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (106, 101, 'E2 T2 115', 38, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (107, 101, 'E2 T2 115', 39, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (102, 116, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (108, 102, 'E1 T1 116', 51, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (109, 102, 'E1 T1 116', 52, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (110, 102, 'E1 T1 116', 38, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (111, 102, 'E1 T1 116', 39, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (103, 116, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (112, 103, 'E2 T2 116', 52, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (113, 103, 'E2 T2 116', 38, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (114, 103, 'E2 T2 116', 39, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (115, 103, 'E2 T2 116', 40, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (104, 117, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (116, 104, 'E1 T1 117', 52, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (117, 104, 'E1 T1 117', 38, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (118, 104, 'E1 T1 117', 39, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (119, 104, 'E1 T1 117', 40, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (105, 117, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (120, 105, 'E2 T2 117', 38, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (121, 105, 'E2 T2 117', 39, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (122, 105, 'E2 T2 117', 40, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (123, 105, 'E2 T2 117', 41, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (106, 118, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (124, 106, 'E1 T1 118', 38, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (125, 106, 'E1 T1 118', 39, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (126, 106, 'E1 T1 118', 40, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (127, 106, 'E1 T1 118', 41, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (107, 118, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (128, 107, 'E2 T2 118', 39, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (129, 107, 'E2 T2 118', 40, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (130, 107, 'E2 T2 118', 41, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (131, 107, 'E2 T2 118', 42, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (108, 119, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (132, 108, 'E1 T1 119', 39, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (133, 108, 'E1 T1 119', 40, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (134, 108, 'E1 T1 119', 41, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (135, 108, 'E1 T1 119', 42, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (109, 119, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (136, 109, 'E2 T2 119', 40, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (137, 109, 'E2 T2 119', 41, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (138, 109, 'E2 T2 119', 42, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (139, 109, 'E2 T2 119', 43, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (110, 120, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (140, 110, 'E1 T1 120', 40, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (141, 110, 'E1 T1 120', 41, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (142, 110, 'E1 T1 120', 42, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (143, 110, 'E1 T1 120', 43, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (111, 120, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (144, 111, 'E2 T2 120', 41, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (145, 111, 'E2 T2 120', 42, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (146, 111, 'E2 T2 120', 43, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (147, 111, 'E2 T2 120', 44, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (112, 121, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (148, 112, 'E1 T1 121', 41, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (149, 112, 'E1 T1 121', 42, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (150, 112, 'E1 T1 121', 43, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (151, 112, 'E1 T1 121', 44, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (113, 121, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (152, 113, 'E2 T2 121', 42, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (153, 113, 'E2 T2 121', 43, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (154, 113, 'E2 T2 121', 44, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (155, 113, 'E2 T2 121', 45, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (114, 122, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (156, 114, 'E1 T1 122', 42, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (157, 114, 'E1 T1 122', 43, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (158, 114, 'E1 T1 122', 44, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (159, 114, 'E1 T1 122', 45, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (115, 122, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (160, 115, 'E2 T2 122', 43, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (161, 115, 'E2 T2 122', 44, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (162, 115, 'E2 T2 122', 45, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (163, 115, 'E2 T2 122', 46, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (116, 123, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (164, 116, 'E1 T1 123', 43, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (165, 116, 'E1 T1 123', 44, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (166, 116, 'E1 T1 123', 45, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (167, 116, 'E1 T1 123', 46, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (117, 123, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (168, 117, 'E2 T2 123', 44, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (169, 117, 'E2 T2 123', 45, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (170, 117, 'E2 T2 123', 46, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (171, 117, 'E2 T2 123', 47, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (118, 124, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (172, 118, 'E1 T1 124', 44, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (173, 118, 'E1 T1 124', 45, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (174, 118, 'E1 T1 124', 46, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (175, 118, 'E1 T1 124', 47, 4);
INSERT INTO Temporada (id_temporada, id_contenido, numero_temporada) VALUES (119, 124, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (176, 119, 'E2 T2 124', 45, 1);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (177, 119, 'E2 T2 124', 46, 2);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (178, 119, 'E2 T2 124', 47, 3);
INSERT INTO Episodio (id_episodio, id_temporada, titulo, duracion, numero_episodio) VALUES (179, 119, 'E2 T2 124', 48, 4);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (100, 101);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (100, 110);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (101, 102);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (101, 107);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (102, 103);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (102, 110);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (103, 104);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (103, 107);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (104, 105);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (104, 110);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (105, 106);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (105, 107);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (106, 107);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (106, 110);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (107, 108);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (107, 107);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (108, 100);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (108, 110);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (109, 101);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (109, 107);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (110, 102);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (110, 110);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (111, 103);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (111, 107);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (112, 104);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (112, 110);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (113, 105);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (113, 107);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (114, 106);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (114, 110);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (115, 100);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (115, 109);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (116, 103);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (116, 109);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (117, 100);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (117, 109);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (118, 103);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (118, 109);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (119, 100);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (119, 109);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (120, 103);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (120, 109);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (121, 100);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (121, 109);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (122, 103);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (122, 109);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (123, 100);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (123, 109);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (124, 103);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (124, 109);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (125, 105);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (125, 110);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (126, 105);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (126, 108);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (127, 105);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (127, 110);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (128, 105);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (128, 108);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (129, 105);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (129, 110);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (130, 105);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (130, 108);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (131, 105);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (131, 110);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (132, 105);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (132, 108);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (133, 109);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (133, 111);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (134, 109);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (134, 111);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (135, 109);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (135, 111);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (136, 109);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (136, 111);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (137, 109);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (137, 111);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (138, 109);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (138, 111);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (139, 109);
INSERT INTO Contenido_genero (id_contenido, id_genero) VALUES (139, 111);
INSERT INTO Contenido_relacionado (id_relacion, id_cont_origen, id_cont_relacion, tipo_relacion, descripcion) VALUES (100, 100, 101, 'MISMO_TEMA', 'Relacion tematica');
INSERT INTO Contenido_relacionado (id_relacion, id_cont_origen, id_cont_relacion, tipo_relacion, descripcion) VALUES (101, 102, 104, 'SIMILAR', 'Relacion tematica');
INSERT INTO Contenido_relacionado (id_relacion, id_cont_origen, id_cont_relacion, tipo_relacion, descripcion) VALUES (102, 105, 106, 'SIMILAR', 'Relacion tematica');
INSERT INTO Contenido_relacionado (id_relacion, id_cont_origen, id_cont_relacion, tipo_relacion, descripcion) VALUES (103, 115, 116, 'MISMA_SERIE', 'Relacion tematica');
INSERT INTO Contenido_relacionado (id_relacion, id_cont_origen, id_cont_relacion, tipo_relacion, descripcion) VALUES (104, 117, 118, 'SIMILAR', 'Relacion tematica');
INSERT INTO Contenido_relacionado (id_relacion, id_cont_origen, id_cont_relacion, tipo_relacion, descripcion) VALUES (105, 120, 121, 'TECNOLOGIA', 'Relacion tematica');
INSERT INTO Contenido_relacionado (id_relacion, id_cont_origen, id_cont_relacion, tipo_relacion, descripcion) VALUES (106, 125, 126, 'REGIONAL', 'Relacion tematica');
INSERT INTO Contenido_relacionado (id_relacion, id_cont_origen, id_cont_relacion, tipo_relacion, descripcion) VALUES (107, 130, 131, 'DOCUMENTAL', 'Relacion tematica');
INSERT INTO Contenido_relacionado (id_relacion, id_cont_origen, id_cont_relacion, tipo_relacion, descripcion) VALUES (108, 135, 136, 'PODCAST', 'Relacion tematica');
INSERT INTO Contenido_relacionado (id_relacion, id_cont_origen, id_cont_relacion, tipo_relacion, descripcion) VALUES (109, 137, 139, 'EDUCATIVO', 'Relacion tematica');
INSERT INTO Contenido_relacionado (id_relacion, id_cont_origen, id_cont_relacion, tipo_relacion, descripcion) VALUES (110, 108, 127, 'REGIONAL', 'Relacion tematica');
INSERT INTO Contenido_relacionado (id_relacion, id_cont_origen, id_cont_relacion, tipo_relacion, descripcion) VALUES (111, 112, 128, 'HISTORIA', 'Relacion tematica');
INSERT INTO Contenido_relacionado (id_relacion, id_cont_origen, id_cont_relacion, tipo_relacion, descripcion) VALUES (112, 119, 132, 'INNOVACION', 'Relacion tematica');
INSERT INTO Contenido_relacionado (id_relacion, id_cont_origen, id_cont_relacion, tipo_relacion, descripcion) VALUES (113, 123, 134, 'AMBIENTAL', 'Relacion tematica');
INSERT INTO Contenido_relacionado (id_relacion, id_cont_origen, id_cont_relacion, tipo_relacion, descripcion) VALUES (114, 110, 138, 'ENTREVISTA', 'Relacion tematica');
COMMIT;
